// El assignments
window.el = el;
window.el.fn = Node.fn;
window.el.hasParent = hasParent;
window.el.contains = contains;
window.el.isElement = isElement;
window.el.isComponent = isComponent;
window.el.isCreateNode = isCreateNode;
window.el.addClass = curry(addClass);
window.el.getNode = getNode;
window.el.version = '1.2.8';
