// El assignments
window.el = el;
window.el.fn = CreateNode.fn;
window.el.hasParent = hasParent;
window.el.contains = contains;
window.el.isElement = isElement;
window.el.isComponent = isComponent;
window.el.isCreateNode = isCreateNode;
window.el.getNode = getNode;
window.el.version = '1.0.3';
